import board

BUTTON_A = board.GP5
BUTTON_B = board.GP4
BUTTON_C = board.GP11
BUTTON_D = board.GP10
BUTTON_ESC = board.GP3
BUTTON_OK = board.GP12
BUTTONS = [BUTTON_A, BUTTON_B, BUTTON_C, BUTTON_D, BUTTON_ESC, BUTTON_OK]
BUTTONS_VALUE_WHEN_PRESSED = False  # True = VCC, False = GND

DISPLAY_HEIGHT = 64
DISPLAY_OFFSET_X = 2
DISPLAY_WIDTH = 128

FONT_HEIGHT = 12
FONT_WIDTH = 6

I2C_ADDRESS_DISPLAY = 0x3C
I2C_ADDRESS_EEPROM = 0x57
I2C_ADDRESS_RTC = 0x68
I2C_SCL = board.GP1
I2C_SDA = board.GP0

LOCALE = "pl"

MOTOR_A_PHASE1 = board.GP18
MOTOR_A_PHASE2 = board.GP19
MOTOR_A_SPEED = board.GP14
MOTOR_B_PHASE1 = board.GP20
MOTOR_B_PHASE2 = board.GP21
MOTOR_B_SPEED = board.GP15
