MOTOR_CLOSE_ID = "c"
MOTOR_OPEN_ID = "o"

DURATION_KEY = "d"
SPEED_KEY = "s"
HOUR_KEY = "h"
MINUTE_KEY = "m"
COUNT_KEY = "c"
RATE_KEY = "r"

DURATION_DEFAULT = 1
SPEED_DEFAULT = 100
HOUR_DEFAULT = 0
MINUTE_DEFAULT = 0
COUNT_DEFAULT = 0
RATE_DEFAULT = 2
